language: ruby
sudo: false
cache: bundler
before_install:
  - gem update --system
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.14.3
rvm:
   - 2.2
   - 2.3.3
   - 2.4.0
